const fs = require("fs");
const path = require("path");
const { withMainActivity } = require("@expo/config-plugins");

// Android 12+'s native SplashScreen icon has a platform-owned "reveal"
// animation apps cannot customize or disable — confirmed by testing that
// overriding the JS-side *exit* transition (SplashScreen.setOptions) had
// zero effect, since the reveal happens on entrance, before any JS runs.
// Some OEM skins (confirmed: Huawei/EMUI) render it as an exaggerated zoom
// that overshoots past the screen edges. Since we can't stop Android from
// animating *something*, this leaves nothing visible to animate: it
// overwrites the splash icon drawables generated by expo-splash-screen's
// own plugin with a fully transparent 1x1 pixel. The actual logo is shown
// by our own JS-controlled CustomSplashScreen instead (see
// src/app/_layout.tsx), which isn't subject to any OS/OEM animation at all.
//
// This piggybacks on withMainActivity (rather than withDangerousMod, which
// is what expo-splash-screen itself uses to write those files) because
// config-plugins runs *all* dangerousMod actions before *any* mod of
// another category — confirmed empirically: reordering this plugin's
// position in app.json's plugins array had no effect on whether it ran
// before or after expo-splash-screen's own dangerousMod, since dangerousMod
// registration order isn't governed by plugins-array order the way you'd
// expect. withMainActivity mods run strictly after all dangerousMods have
// completed, which reliably guarantees the splash drawables already exist
// by the time this runs, regardless of array position.
// Verified transparent (pixel(0,0) alpha=0 after a disk round-trip) —
// a previous version of this string was, on inspection, actually an
// OPAQUE BLACK pixel (alpha=255), which is why the "fix" first shipped
// as a visible black box being animated instead of nothing at all.
const TRANSPARENT_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAALSURBVBhXY2AAAgAABQABqtXIUQAAAABJRU5ErkJggg==";

module.exports = function withTransparentSplashIcon(config) {
  return withMainActivity(config, (config) => {
    const resDir = path.join(config.modRequest.platformProjectRoot, "app/src/main/res");
    const densities = ["mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"];
    const buffer = Buffer.from(TRANSPARENT_PNG_BASE64, "base64");
    for (const density of densities) {
      const filePath = path.join(resDir, `drawable-${density}`, "splashscreen_logo.png");
      if (fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, buffer);
      }
    }
    return config;
  });
};
